---
  - name: Remove Docker from MacOS Quarrantine
    command: xattr -d -r com.apple.quarantine /Applications/Docker.app

  - name: Stop Docker gracefully (if already running)
    command: osascript -e 'quit app "Docker"'

  - name: Install Docker Networking Components - PrivilegedHelperTools
    become: true
    synchronize:
      src: "{{ docker_app_paths_for_privilegedhelpertools.src }}"
      dest: "{{ docker_app_paths_for_privilegedhelpertools.dest }}"

  - name: Install Docker Networking Components - PrivilegedHelperTools Ownership
    become: true
    file:
      path: "{{ docker_app_paths_for_privilegedhelpertools.dest }}"
      owner: root
      group: wheel
      mode: 0544

  - name: Install Docker Networking Components - LaunchDaemons
    become: true
    synchronize:
      src: "{{ docker_app_paths_for_launchdaemons.src }}"
      dest: "{{ docker_app_paths_for_launchdaemons.dest }}"

  - name: Install Docker Networking Components - LaunchDaemons Ownership
    become: true
    file:
      path: "{{ docker_app_paths_for_launchdaemons.dest }}"
      owner: root
      group: wheel
      mode: 0644

  - name: Launch Docker Networking Components
    become: true
    command: launchctl load "{{ docker_app_paths_for_launchdaemons.dest }}"

  - name: Launch Docker
    command: open --background -a Docker
