---
  - name: Detect if Docker is Quarantined
    ignore_errors: yes
    changed_when: false
    command: xattr -p com.apple.quarantine /Applications/Docker.app
    register: quarantined_docker

  - name: Remove Docker from MacOS Quarantine
    command: xattr -d -r com.apple.quarantine /Applications/Docker.app
    when: quarantined_docker is success

    # xattr:
    #   path: /Applications/Docker.app
    #   key: com.apple.quarantine
    #   state: absent

  - name: Detect if Docker is already running
    ignore_errors: yes
    changed_when: false
    command: pgrep -xq -- "Docker"
    register: running_docker

  - name: Stop Docker gracefully
    when: running_docker is success
    command: osascript -e 'quit app "Docker"'

  - name: Install Docker Networking Components - PrivilegedHelperTools
    become: true
    synchronize:
      src: "{{ docker_app_paths_for_privilegedhelpertools.src }}"
      dest: "{{ docker_app_paths_for_privilegedhelpertools.dest }}"

  - name: Install Docker Networking Components - PrivilegedHelperTools Ownership
    become: true
    file:
      path: "{{ docker_app_paths_for_privilegedhelpertools.dest }}"
      owner: root
      group: wheel
      mode: 0544

  - name: Install Docker Networking Components - LaunchDaemons
    become: true
    synchronize:
      src: "{{ docker_app_paths_for_launchdaemons.src }}"
      dest: "{{ docker_app_paths_for_launchdaemons.dest }}"

  - name: Install Docker Networking Components - LaunchDaemons Ownership
    become: true
    file:
      path: "{{ docker_app_paths_for_launchdaemons.dest }}"
      owner: root
      group: wheel
      mode: 0644

  - name: Launch Docker Networking Components
    become: true
    changed_when: false
    command: launchctl load "{{ docker_app_paths_for_launchdaemons.dest }}"

  - name: Detect if Docker is running
    ignore_errors: yes
    changed_when: false
    command: pgrep -xq -- "Docker"
    register: running_docker

  - name: Launch Docker
    when: running_docker is failed
    command: open --background -a Docker
